// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;

public class MyFisrtTest {
  public WebDriver driver;

  @Before

  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    driver.manage().window().maximize();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void clickOnce() {
    driver.get("https://furbo.sk/playground/clickmebaby.php");
    driver.manage().window().setSize(new Dimension(1200, 777));
    Assert.assertEquals("0", driver.findElement(By.id("clicks")).getText());
    Assert.assertEquals("klikov", driver.findElement(By.className("description")).getText());
    for (int i = 1; i < 11; i++) {
      driver.findElement(By.id("clickMe")).click();
      Assert.assertEquals(String.valueOf(i), driver.findElement(By.id("clicks")).getText());
      if (i==1) {
        Assert.assertEquals("klik", driver.findElement(By.className("description")).getText());
      }
      if (i > 1 && i <= 4) {
        Assert.assertEquals("kliky", driver.findElement(By.className("description")).getText());
      }
      if (i > 4) {
        Assert.assertEquals("klikov", driver.findElement(By.className("description")).getText());
      }
    }
  }

  //JUnit framework je zodpovedny za overovanie ocakavneho vs aktualneho vysleedku
}
