// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;

public class SelectTest {
  public WebDriver driver;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    driver.manage().window().maximize();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  // value sa používa na to, aby som mohla ziskat hodnotu moznosti a nasledne s nou viem pracovat
  // ideme vyberat z kombo boxu
  // select by index

  // value zadavame vzdy ako string
  @Test
  public void clickOnce() {
    driver.get("https://furbo.sk/playground/vybersi.php");
    new Select(driver.findElement(By.className("form-control"))).selectByIndex(1);
    new Select(driver.findElement(By.className("form-control"))).selectByValue("02");
    new Select(driver.findElement(By.className("form-control"))).selectByVisibleText("Pikachu");
    Assert.assertTrue(driver.findElement(By.xpath("//div/div[2]/h3")).getText().contains("Pikachu"));
    Assert.assertFalse(driver.findElement(By.xpath("//div/div[2]/h3")).getText().contains("Pikaču"));
  }


  // pozname 3 zakladne typy assertov
  // assert equals - porovnava 2 retazce
  // assert true a assert false
  @After
  public void tearDown() {
    driver.quit();
  }
}
